server:
  error:
    include-message: always
spring:
  main:
    # Required for the security package
    allow-bean-definition-overriding: true
fhir:
  resultCount: 50

# this is the default 'development' trial site config - CCO/REGION/COUNTRY/LCC
mts:
  site:
    name: Organization
    displayName: site
    type: CCO
    attributes:
      - name: name
        displayName: Name
        validationRegex: '^[a-zA-Z\s]{1,35}$'
      - name: alias
        displayName: Alias
        validationRegex: '^[a-zA-Z\s]{1,35}$'
      - name: parentSiteId
        displayName: Parent Site Id
        validationRegex: ''
      - name: siteType
        displayName: Site Type
        validationRegex: ''
    child:
      - name: Organization
        displayName: site
        type: REGION
        attributes:
          - name: name
            displayName: Name
            validationRegex: '^[a-zA-Z\s]{1,35}$'
          - name: alias
            displayName: Alias
            validationRegex: '^[a-zA-Z\s]{1,35}$'
          - name: parentSiteId
            displayName: Parent Site Id
            validationRegex: ''
          - name: siteType
            displayName: Site Type
            validationRegex: ''
        child:
          - name: Organization
            displayName: site
            type: COUNTRY
            attributes:
              - name: name
                displayName: Name
                validationRegex: '^[a-zA-Z\s]{1,35}$'
              - name: alias
                displayName: Alias
                validationRegex: '^[a-zA-Z\s]{1,35}$'
              - name: parentSiteId
                displayName: Parent Site Id
                validationRegex: ''
              - name: siteType
                displayName: Site Type
                validationRegex: ''
            child:
              - name: Organization
                displayName: site
                type: LCC
                attributes:
                  - name: name
                    displayName: Name
                    validationRegex: '^[a-zA-Z\s]{1,35}$'
                  - name: alias
                    displayName: Alias
                    validationRegex: '^[a-zA-Z\s]{1,35}$'
                  - name: parentSiteId
                    displayName: Parent Site Id
                    validationRegex: ''
                  - name: siteType
                    displayName: Site Type
                    validationRegex: ''
